In [3]:
import pandas as pd
# pd.__version__

In [4]:
#Read the CSV File into df
df = pd.read_csv('../clean.csv')
df.head()

,Unnamed: 0,category,company_name,job_description,job_title,job_type,location,post_date,salary_offered,views
0,17,"Pharmaceutical, Healthcare and Medical Sales",Kirkham Young Ltd,Business Development Manager - Medical IT\nThi...,Sales Specialist,Permanent,UK,4/16/2018,NaN,1181
1,35,"Pharmaceutical, Healthcare and Medical Sales",Kirkham Young Ltd,Sales Specialist - Interventional Cardiac Dev...,Sales Specialist,Permanent,London,4/12/2018,Neg,555
2,46,"Pharmaceutical, Healthcare and Medical Sales",BMS Performance,This is a fantastic opportunity for a strateg...,Regional Sales Manager,Permanent,Europe,4/16/2018,NaN,635
3,58,"Pharmaceutical, Healthcare and Medical Sales",Silchester Associates Ltd,"Our client is a leading manufacturer, wholesal...",Pharmaceutical Wholesale,Permanent,Birmingham,4/11/2018,NaN,2018
4,66,"Pharmaceutical, Healthcare and Medical Sales",ID Search and Selection Ltd,Our client is a boutique agency delivering hig...,Senior Account Manager,Permanent,South East,4/13/2018,NaN,1099

In [8]:
#Calculate the number of views garnered by the 70th percentile job
m = df['views'].quantile(0.70)
m
#We can see that only 30% of the movies have gained more than 1788 views. Therefore, our value of m is 1788

1788.0

In [14]:
data = df

In [10]:
# Calculate C
C = df['views'].mean()
C

1279.469581248354

In [12]:
# Function to compute the Job weighted views for each position
def weighted_rating(x, m=m, C=C):
    v = x['views']
    R = x['views_average']
    # Compute the weighted score
    return (v/(v+m) * R) + (m/(m+v) * C)

In [15]:
# Compute the score using the weighted_rating function defined above
data['score'] = data.apply(weighted_rating, axis=1)

KeyError: ('vote_average', 'occurred at index 0')

In [16]:
#Sort movies in descending order of their scores
q_movies = q_movies.sort_values('score', ascending=False)

#Print the top 25 movies
q_movies[['title', 'vote_count', 'vote_average', 'score', 'runtime']].head(25)

,title,vote_count,vote_average,score,runtime
10309,Dilwale Dulhania Le Jayenge,661.0,9.1,8.855148,190.0
314,The Shawshank Redemption,8358.0,8.5,8.482863,142.0
834,The Godfather,6024.0,8.5,8.476278,175.0
40251,Your Name.,1030.0,8.5,8.366584,106.0
12481,The Dark Knight,12269.0,8.3,8.289115,152.0
2843,Fight Club,9678.0,8.3,8.286216,139.0
292,Pulp Fiction,8670.0,8.3,8.284623,154.0
522,Schindler's List,4436.0,8.3,8.270109,195.0
23673,Whiplash,4376.0,8.3,8.269704,105.0
5481,Spirited Away,3968.0,8.3,8.266628,125.0
2211,Life Is Beautiful,3643.0,8.3,8.263691,116.0
1178,The Godfather: Part II,3418.0,8.3,8.261335,200.0
1152,One Flew Over the Cuckoo's Nest,3001.0,8.3,8.256051,133.0
1176,Psycho,2405.0,8.3,8.245381,109.0
351,Forrest Gump,8147.0,8.2,8.184252,142.0
1184,Once Upon a Time in America,1104.0,8.3,8.183804,229.0
1154,The Empire Strikes Back,5998.0,8.2,8.178656,124.0
18465,The Intouchables,5410.0,8.2,8.176357,112.0
289,Leon: The Professional,4293.0,8.2,8.170276,110.0
3030,The Green Mile,4166.0,8.2,8.169381,189.0
1170,GoodFellas,3211.0,8.2,8.160414,145.0
2216,American History X,3120.0,8.2,8.159278,119.0
1161,12 Angry Men,2130.0,8.2,8.140785,96.0
9698,Howl's Moving Castle,2049.0,8.2,8.138499,119.0
2884,Princess Mononoke,2041.0,8.2,8.138264,134.0